name: nexar
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==2.7.13
    - numpy>=1.13.1
    - matplotlib
    - opencv3
    - pillow>=2.2.1
    - h5py
    - attrdict>=2.0.0
    - python-socketio>=1.6.1
    - seaborn
    - pandas
    - ffmpeg
    - imageio=2.1.2
    - pyqt=4.11.4
    - pip:
        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0-cp27-none-linux_x86_64.whl
        - keras==2.0.4
        - monotonic
        - easydict==1.6
        - joblib==0.10.3
        - shapely
        - Cython
        - requests
        - lxml
